### ISSUE TITLE
problema no dotenv

### ISSUE THREAD

**Issue by wgnann** [Transparencia-Brasil/achados-e-pedidos-importador#10]
o `dotenv` não pega variáveis de ambiente. ele as obtém a partir de um arquivo .env, que está fora do deploy.

talvez compense usar `os.environ.get()` em vez de `dotenv.get_key()`

**Comment by studiocuboweb** [comment]
@wgnann mudamos para os.getenv conforme pull request https://github.com/Transparencia-Brasil/achados-e-pedidos-importador/pull/12

fechando o ticket
