### ISSUE TITLE
[migracao-azure] database is locked ao se logar

### ISSUE THREAD

**Issue by studiocuboweb** [Transparencia-Brasil/achados-e-pedidos-importador#11]
Ao entrar no endereço https://transparencia-achados-importador.azurewebsites.net/ e tentar se logar, da erro:

````
<h1 style="padding: 0px; margin: 0px; font-weight: normal; color: rgb(0, 0, 0); font-family: sans-serif; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">OperationalError at /importer/login/</h1><pre class="exception_value" style="padding: 0px; margin: 10px 0px; font-size: 1.5em; white-space: pre-wrap; font-family: sans-serif; color: rgb(102, 102, 102); font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">database is locked</pre>

Request Method: | POST
-- | --
http://transparencia-achados-importador.azurewebsites.net/importer/login/
2.0.1
OperationalError
database is locked
/tmp/8d96d8393c234d3/antenv3.6/lib/python3.6/site-packages/django/db/backends/base/base.py in _commit, line 239
/opt/python/3.6.12/bin/python3.6
3.6.12
['/opt/python/3.6.12/bin',  '/home/site/wwwroot',  '/tmp/8d96d8393c234d3/antenv3.6/lib/python3.6/site-packages',  '/opt/python/3.6.12/lib/python36.zip',  '/opt/python/3.6.12/lib/python3.6',  '/opt/python/3.6.12/lib/python3.6/lib-dynload',  '/opt/python/3.6.12/lib/python3.6/site-packages',  '/home/site/wwwroot',  '/var/www/importador.achadosepedidos.org.br/achadosepedidos.org.br-importador',  '/var/www/importador.achadosepedidos.org.br/achadosepedidos.org.br-importador/achadosepedidos']
Qua, 1 Set 2021 19:11:11 -0300
````

A base de dados que armazena o login é um sqlite...

Além disso, o log completo expõe a senha. Lembrar de desligar o debug em produção. Por isso estou colocando só a parte principal.

![Screen Shot 2021-09-01 at 18 58 22](https://user-images.githubusercontent.com/32527574/131752316-e6918c66-4e81-4285-9bdc-077b63e4d4d4.png)

**Comment by studiocuboweb** [comment]
@wgnann mais uma treta...

**Comment by wgnann** [comment]
Parece haver alguma coisa travando o banco de dados.

Um teste possível seria alterar seu docker para tentar acessar o banco na Azure.

Outro teste é deixar o importador da Azure sem banco "staging" e configurar o staging como principal E configurar o importador na Google sem banco staging. Daí, como não há acesso ao mesmo banco, se o erro for o descrito pela imagem, ele não deve acontecer.

**Comment by studiocuboweb** [comment]
Acho que esse problema não está acontecendo no mysql e sim no sqlite. Dentro do projeto existe essa base em sqlite:
importadorDB.sqlite3 (está no github.)

Esse erro acontece no login e é no sqlite que estão armazenadas as credenciais de acesso.

creio que seja algo relacionado com isso:
https://stackoverflow.com/questions/53226642/sqlite3-database-is-locked-in-azure

**Comment by wgnann** [comment]
rodei o 'sqlite3 <database-file> 'PRAGMA journal_mode=wal;'. pode verificar se funcionou?

de qualquer forma, o correto mesmo é parar de usar sqlite.

**Comment by studiocuboweb** [comment]
funcionou. fechando o issue.

muito obrigado
