### ISSUE TITLE
[migracao-azure] Pasta static onde estão os assets está fora da pasta da aplicação. Precisa estar dentro dela

### ISSUE THREAD

**Issue by studiocuboweb** [Transparencia-Brasil/achados-e-pedidos-importador#6]
O Will migrou o importador do Google Cloud para a Azure e forneceu essa URL de teste:
https://transparencia-achados-importador.azurewebsites.net

Ao acessar essa URL constatamos que alguns assets servidos pela pasta static (ex: https://transparencia-achados-importador.azurewebsites.net/static/importer/login.css) não estão sendo encontrados (erro 404)

esse problema acontece porque essa pasta está fora do root da aplicação e configurada pelo Apache através de um redirecionamento. Quando a URL possuir /static os arquivos estão em static/ e ao acessar a aplicação os arquivos estão em achadosepedidos/ conforme essa estrutura
./
static/
achadosepedidos/

Precisamos colocar o static dentro da pasta achadosepedidos/ para essa pasta conseguir ser encontrada pela URL e servir os estilos do site corretamente
![Screen Shot 2021-08-04 at 17 20 51](https://user-images.githubusercontent.com/32527574/128249341-24a6e9c8-8038-4f93-9345-3d3221b65b27.png)

**Comment by wgnann** [comment]
É um pouco pior do que parece. O que é sugerido é usar o [whitenoise](https://devcenter.heroku.com/articles/django-assets) para servir o conteúdo.

Além disso, o conteúdo que importa para efeito do `manage.py collectstatic` é o que está em `importer/static/importer` e não o que está em `static/importer`.

De qualquer forma, agora há um caminho.

**Comment by studiocuboweb** [comment]
@wgnann creio que resolvemos o problema do static.
Instalamos o whitenoise e montamos um docker com todos os serviços para testar local.

Os assets agora estão sendo carregados corretamente:
![Screen Shot 2021-08-31 at 19 09 51](https://user-images.githubusercontent.com/32527574/131582305-0efd29c4-511f-4109-8330-80efd2687f99.png)

Consegui inclusive me logar na aplicação, mas não cheguei a testar o upload / import dos arquivos.

Para fazer funcionar no docker nós recalibramos todas as dependências novamente.

Aqui está o pull request: #8 

Com isso vc acha que já resolvemos essa questão?

**Comment by studiocuboweb** [comment]
Atualização:

Configurei o banco do azure stage no docker e consegui fazer upload de 1 pedido desta planilha no meu computador local:
[Transparencia Brasil.csv](https://github.com/Transparencia-Brasil/achados-e-pedidos-importador/files/7087182/Transparencia.Brasil.csv)

Veja o print:
![Screen Shot 2021-08-31 at 20 03 56](https://user-images.githubusercontent.com/32527574/131586813-ef853eab-1acc-4a84-8978-07627a586a4f.png)

Dessa forma daria para rodar de qualquer lugar :p 


Então creio que está tudo funcionando!

**Comment by studiocuboweb** [comment]
Will conseguiu buildar o importador e a pasta esta static agora está sendo servida no endereço do azure:
https://transparencia-achados-importador.azurewebsites.net/

fechando esse issue
