### ISSUE TITLE
problema do celery vs vine

### ISSUE THREAD

**Issue by wgnann** [Transparencia-Brasil/achados-e-pedidos-importador#9]
Na hora de fazer deploy não funciona.
remote: celery 4.4.7 has requirement vine==1.3.0, but you'll have vine 5.0.0 which is incompatible.

Depois disso:
remote: ModuleNotFoundError: No module named 'vine.five'

**Comment by wgnann** [comment]
requirements.txt que rodou:
```
amqp==2.3.2
astroid==1.6.5
autopep8==1.4.3
billiard==3.5.0.5
celery==4.2.1
Django==2.0.1
isort==4.3.4
kombu==4.2.2.post1
lazy-object-proxy==1.3.1
mccabe==0.6.1
mysqlclient==1.3.10
pycodestyle==2.4.0
pytz==2018.9
rabbitmq==0.2.0
redis==3.0.1
six==1.12.0
vine==1.2.0
wrapt==1.10.11
whitenoise==5.3.0
```

**Comment by marcelo-jrkiko** [comment]
Olá, Retire a Especificação das versões nos requirements:

```
amqp
astroid==1.6.5
autopep8==1.4.3
billiard
celery==4.4.7
Django==2.0.1
isort==4.3.4
kombu
lazy-object-proxy==1.3.1
mccabe==0.6.1
pycodestyle==2.4.0
pytz==2018.9
rabbitmq==0.2.0
redis==3.0.1
six==1.12.0
vine
wrapt==1.10.11
python-dotenv==0.19.0
whitenoise==5.3.0
mysqlclient
```

Assim o PIP vai resolver sozinha as versões. A questão não é a versão do python,pois ambos são 3.6. Mas a versão do VINE é muito antiga.

**Comment by studiocuboweb** [comment]
@wgnann @marcelo-jrkiko Problema de retirar a especificação de versão do vine é que funciona no build do docker, mas não funciona no build da azure. A configuração do requirements.txt que funcionou para o Docker e para o build do azure é essa:

````
amqp==2.3.2
astroid==1.6.5
autopep8==1.4.3
billiard==3.5.0.5
celery==4.2.1
Django==2.0.1
isort==4.3.4
kombu==4.2.2.post1
lazy-object-proxy==1.3.1
mccabe==0.6.1
mysqlclient
pycodestyle==2.4.0
python-dotenv==0.19.0
pytz==2018.9
rabbitmq==0.2.0
redis==3.0.1
six==1.12.0
vine==1.2.0
wrapt==1.10.11
whitenoise==5.3.0
````

conforme esse commit: https://github.com/Transparencia-Brasil/achados-e-pedidos-importador/commit/fd39576dcfd5433d975b8017131a44bdf5458efa

Procedimentos para configurar o build para a azure:

````
git remote add azure https://transparencia-git@transparencia-achados-importador.scm.azurewebsites.net/transparencia-achados-importador.git
````
````
git push azure master --force
````

Agora o build do importador para o Azure funcionou conforme imagem:
![Screen Shot 2021-09-08 at 10 23 43](https://user-images.githubusercontent.com/32527574/132518962-9201b724-0fd6-42eb-9f6c-53d3cead1858.png)

Também funcionou no docker.

Após o build eu entro no importador que está hospedado no Azure:
https://transparencia-achados-importador.azurewebsites.net/

Faço o login. e acontece o erro deste issue:
https://github.com/Transparencia-Brasil/achados-e-pedidos-importador/issues/11

Por eu ter conseguido dar o build no Azure, creio que este issue "problema do celery vs vine" está encerrado e por isso estou fechando.

Para finalizar os testes, fica pendente olhar o issue: https://github.com/Transparencia-Brasil/achados-e-pedidos-importador/issues/11

A base do sqlite fica no github aqui:
importadorDB.sqlite3
